website_forum_faq_edit/__init__.py
website_forum_faq_edit/__openerp__.py
website_forum_faq_edit/views.xml

THis addon allows you to edit FAQ guidlines either
to debrand or customize

website_forum_faq_edit: Edit FAQ Guidelines

---

web_login_background/README.rst
web_login_background/__init__.py
web_login_background/__openerp__.py
web_login_background/controllers.py
web_login_background/models.py
web_login_background/templates.xml
web_login_background/views/attachment.xml

[ADD] web_login_background module

---

website_sale_search_custom/README.rst
website_sale_search_custom/__init__.py
website_sale_search_custom/__openerp__.py
website_sale_search_custom/models.py
website_sale_search_custom/query_url.py

It allows to avoid monkey pathes in databases where this module is not installed

[FIX] use post_load website_sale_search_custom

---

website_booking_calendar/controllers/main.py
website_booking_calendar/models.py
website_booking_calendar/static/src/css/website_booking_calendar.css
website_booking_calendar/static/src/js/website_booking_calendar.js

* display booked slots on online form
* filter products by venue
* pricelists

8.0 booking calendar

---

website_sale_available/website_sale_available_views.xml

Hi @yelizariev . This PR fix and error raised when you install website_sale_available together with website_sale_options.
Thanks!

[FIX] compatibility of website_sale_available with website_sale_options

---

web_login_background/templates.xml

it fixes compatibility with web_debranding

[FIX] set higher priority for login_layout

---

.gitignore

* Add .gitignore for common python files that shouldn't be track by VCS

[ADD] website-addons: Add .gitignore

---

website_sale_stock_status/__openerp__.py
website_sale_stock_status/website_sale_stock_status_data.xml
website_sale_stock_status/website_sale_stock_status_views.xml

Hello!
I've gone ahead and upgraded this module for use with 9.0. I also made some changes to the directory structure. My apologies for the unclean diff - let me know if there's anything I can clarify or do to help.
Thanks!

[MIG] website_sale_stock_status: Upgrade to 9.0

---

website_sale_search_clear/static/description/index.html

[ADD] Stamp to website_sale_search_clear

[ADD] Stamp to website_sale_search_clear

---

website_booking_calendar/controllers/main.py
website_booking_calendar/static/src/js/website_booking_calendar.js

This depends on https://github.com/it-projects-llc/website-addons/pull/163 and includes its commits. You have to review only commit e9bcae0

8.0 thecage expired bug 200217

---

website_sale_add_to_cart/__openerp__.py

[DOC] New price for website_sale_add_to_cart

[DOC] New price for website_sale_add_to_cart

---

website_sale_add_to_cart/__openerp__.py

[DOC][10.0] New price for website_sale_add_to_cart

[DOC][10.0] New price for website_sale_add_to_cart

---

stock_picking_barcode/__openerp__.py

[DOC] stock_picking_barcode - new price

[DOC] stock_picking_barcode - new price

---

website_sale_checkout_store/controllers/main.py

[FIX] current user may not have aces to read and write sale.order

---

website_multi_company/doc/index.rst
website_multi_company/static/description/index.html

[DOC] website_multi_company: added info about dbfilter_from_header module

[DOC] website_multi_company: added info about dbfilter_from_header module

---

website_multi_company/doc/index.rst

[DOC] website_multi_company: edit index.rst

[DOC] website_multi_company: edit index.rst

---

website_proposal/models.py

- Just a small typo in website_proposal 10.0

[FIX] typo in website_proposal

---

stock_picking_barcode/static/description/index.html

[DOC] stock_picking_barcode: stamps

[DOC] stock_picking_barcode: stamps

---

website_multi_company/__manifest__.py

[REM] website_multi_company: remove unneeded demo images

[REM] website_multi_company: remove unneeded demo images

---

web_login_background/__openerp__.py
web_login_background/models.py
website_booking_calendar/__openerp__.py
website_booking_calendar/controllers/main.py
website_booking_calendar/models.py
website_files/__openerp__.py
website_files/controllers/website_files.py
website_multi_company/__manifest__.py
website_multi_company_demo/models/res_users.py
website_sale_available_fake/__openerp__.py
website_sale_available_fake/website_sale_available_fake_models.py
website_sale_search_clear/__openerp__.py
website_sale_search_clear/query_url.py
website_sales_team/__openerp__.py
website_sales_team/controllers/website_sales_team.py

- Begin to migrate to V11 and python 3

[WIP] 11.0 migrate python3

---

website_multi_company/__manifest__.py
website_multi_company_sale/__manifest__.py

add website_multi_company_sale to website_multi_company's demo_addons

[DEMO] add live_test_url,

---

website_multi_company_sale/doc/index.rst
website_multi_company_sale/static/description/index.html

[DOC] website_multi_company_sale: fixes for documentation

[10.0][DOC] website_multi_company_sale: fixes for documentation

---

website_multi_company_sale/static/description/index.html

Enable Tested on Odoo11.0 enterprise status

Enable Tested on Odoo11.0 enterprise status

---

website_multi_company/doc/index.rst

[DOC] index.rst: apache configuration

[DOC] index.rst: apache configuration

---

website_multi_company/models/module.py

[ADD] website_multi_company: additional base modules

[ADD] website_multi_company: additional base modules

---

stock_picking_barcode/static/description/index.html

change version (Tested in Odoo 11.0) for stock_picking_barcode module

[DOC] change version

---

website_sale_checkout_store/__manifest__.py

[FIX] manifest file: no need to auto install the module

[11.0][FIX] manifest file: no need to auto install the module

---

website_debranding/__init__.py
website_sale_clear_cart/__init__.py

they had lint warningn "no utf8"

[LINT] remove empty files

---

oca_dependencies.txt
website_debranding/__openerp__.py
website_debranding/doc/changelog.rst
website_debranding/doc/index.rst
website_debranding/views.xml
website_multi_company/README.rst
website_multi_company/__manifest__.py
website_multi_company/models/module.py
website_multi_company/models/website.py
website_multi_company/models/website_theme.py
website_multi_company/views/res_config_views.xml
website_multi_company/views/website_theme_views.xml
website_multi_company/views/website_views.xml

<s>Depends on https://github.com/OCA/website/pull/457</s>
Contains patch from https://github.com/OCA/website/pull/456

10.0 website multi company subthemes

---

website_multi_company/__manifest__.py
website_multi_company/models/website_theme.py

see https://github.com/OCA/website/pull/456

[REM] patch that is a part of website_multi_theme

---

website_sale_checkout_store/static/src/js/website_sale_tour_mandatory_1.js
website_sale_checkout_store/static/src/js/website_sale_tour_mandatory_2.js
website_sale_checkout_store/static/src/js/website_sale_tour_mandatory_3.js
website_sale_checkout_store/static/src/js/website_sale_tour_mandatory_4.js

Otherwise it shows errors in other tests
Error: Service website_sale_checkout_store.tour already defined

:rainbow: use unique names in website_sale_checkout_store tours

---

website_multi_company/__manifest__.py
website_multi_company/doc/changelog.rst
website_multi_company/doc/index.rst
website_multi_company/models/__init__.py
website_multi_company/models/ir_ui_view.py
website_multi_company/static/src/js/web_editor.js
website_multi_company/static/src/js/web_editor.tour.js
website_multi_company/static/src/xml/web_editor.xml
website_multi_company/tests/__init__.py
website_multi_company/tests/test_make_multi_website.py
website_multi_company/tests/test_web_editor.py
website_multi_company/views/assets.xml

Will be rebased after https://github.com/it-projects-llc/website-addons/pull/356.
See only update
**New:** Convert view to multi-view via *HTML/CSS Editor*

11.0 convert view to multi via editor

---

website_multi_company_sale/__manifest__.py
website_multi_company_sale/doc/changelog.rst
website_multi_company_sale/doc/index.rst
website_multi_company_sale/models/__init__.py
website_multi_company_sale/models/res_country.py
website_multi_company_sale/models/website.py
website_multi_company_sale/views/website_views.xml

... is configurable per website

:zap: List of available countries on billing address page

---

stock_picking_barcode/README.rst
stock_picking_barcode/__openerp__.py
stock_picking_barcode/doc/changelog.rst
stock_picking_barcode/doc/index.rst

A detailed description of the Barcode scanner support for Stock Picking
module work.

Update Readme.rst for stock_picking_barcode

---

website_multi_company/doc/index.rst

:book: website_multi_company: instruction about Base Url

:book: website_multi_company: instruction about Base Url

---

product_price_factor/__manifest__.py
product_price_factor/models/product.py
product_price_factor/views/product_view.xml

rename models and fields in product_price_factor to changes in v12.

port: port modules to v12

---

product_price_factor_online/__manifest__.py
website_event_attendee_signup/__manifest__.py
website_sale_buy_now/__manifest__.py
website_sale_search_clear/__manifest__.py
website_sale_search_tags/__manifest__.py

If you made a contribution and don't agree with this change please open an issue

:book: Distribute under MIT license

---

website_sale_checkout_store/__manifest__.py
website_sale_checkout_store/controllers/main.py
website_sale_checkout_store/doc/changelog.rst

during the last merge, we accidentally didn’t notice how we lost the change from here https://github.com/itpp-labs/website-addons/pull/430

:ambulance: fix redirection and mandatory fields(re-commit)

---

website_sale_checkout_store/__manifest__.py
website_sale_checkout_store/controllers/main.py
website_sale_checkout_store/doc/changelog.rst

Transfer changes from 12.0
Probably solves #337

:ambulance: fix redirection and mandatory fields

---

website_sale_add_to_cart_disable/__manifest__.py
website_sale_add_to_cart_disable/doc/changelog.rst
website_sale_add_to_cart_disable/doc/index.rst
website_sale_add_to_cart_disable/static/src/css/website_sale_add_to_cart_disable.css
website_sale_add_to_cart_disable/templates.xml

while solving #172 I discovered that the module is referencing website_sale_stock_status which is removed during module cleaning (#507)

:ambulance: transfer styles from the removed module website_sale_stock_status

---

website_event_require_login/README.rst
website_event_require_login/__init__.py
website_event_require_login/__manifest__.py
website_event_require_login/views/website_event_sale_templates.xml

:arrow_up::one::two: website_event_require_login

---

website_sale_cache/README.rst
website_sale_cache/__manifest__.py
website_sale_cache/doc/changelog.rst
website_sale_cache/models.py
website_sale_cache/views.xml

:ambulance: website_sale_cache: active category was not highlighted

---

portal_event_tickets/README.rst
portal_event_tickets/__manifest__.py
portal_event_tickets/controllers/main.py
portal_event_tickets/data/mail_template_data.xml
portal_event_tickets/data/res_users_demo.xml
portal_event_tickets/doc/index.rst
portal_event_tickets/models/event.py
portal_event_tickets/models/event_mail.py
portal_event_tickets/models/event_registration.py
portal_event_tickets/models/sale_order.py
portal_event_tickets/models/website.py
portal_event_tickets/static/src/js/ticket_change.tour.js
portal_event_tickets/static/src/js/ticket_transfer.tour.js
portal_event_tickets/tests/common.py
portal_event_tickets/tests/test_ticket_change.py
portal_event_tickets/tests/test_ticket_transfer.py
portal_event_tickets/views/assets_demo.xml
portal_event_tickets/views/event_event.xml
portal_event_tickets/views/event_registration.xml
portal_event_tickets/views/portal_templates.xml
website_sale_refund/README.rst
website_sale_refund/__manifest__.py
website_sale_refund/doc/index.rst
website_sale_refund/views/website_sale_templates.xml

:arrow_up::one::two: portal_event_tickets

---

README.md

I am sorry to bother you but I'll be honest I am doing this for the hacktoberfest and I''ll be very grateful if you''ll accept my pull 
request , there are some minor changes only in the readme file that I have made which just make it look a little better, thank you so much.

Some minor changes in the readme file
